# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='방 이미지'),
        ),
    ]
