# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 일시')),
                ('score_hard', models.IntegerField(default=0, null=True, verbose_name='방 난이도 점수')),
                ('score_star', models.IntegerField(default=0, null=True, verbose_name='방 별점')),
                ('author', models.CharField(max_length=20, verbose_name='댓글 작성자')),
                ('content', models.CharField(max_length=150, verbose_name='댓글 내용')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_review_set', to='cafe.Room')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='hard',
            name='room',
        ),
        migrations.RemoveField(
            model_name='star',
            name='room',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Hard',
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
