# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0004_auto_20170214_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 일시')),
                ('eval_good', models.IntegerField(default=0, verbose_name='좋아요')),
                ('eval_difficult', models.IntegerField(default=0, verbose_name='어려워요')),
                ('eval_angry', models.IntegerField(default=0, verbose_name='화나요')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_hard',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_star',
        ),
        migrations.RemoveField(
            model_name='room',
            name='score_star',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_evaluation_set', to='cafe.Room'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
