# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_id', models.CharField(max_length=20, verbose_name='아이디')),
                ('login_pw', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('gender', models.BooleanField(default=True)),
                ('nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
